### ISSUE TITLE
Crashing with unexpected error

### ISSUE THREAD

**Issue by Arch23** [ecsanchesjr/ProjetoSeguranca#1]
The program crashes when trying to login after using the logout button.

**Comment by ecsanchesjr** [comment]
This bug is happening with me too.

**Comment by Arch23** [comment]
When the users has no items in the program the bug doesn't happen.

**Comment by gabriel-de-abreu** [comment]
The vectors containing the UI elements references weren't being fully erased when exiting the program.
Hence, when the clear function was called again, the function was trying to clear a vector with broken references of the elements, thus causing the program to crashes.
