### ISSUE TITLE
Various errors with "FileIntegrityNotAssured"

### ISSUE THREAD

**Issue by ecsanchesjr** [ecsanchesjr/ProjetoSeguranca#10]
1) Actions
a) I created the user
b) Changed one whatever byte in file
c) Try to add a new entry
d) The program throws the exception of Integrity 
e) The program "stop" and my user continue logged 

2) Actions
a) I created the user
b) Changed one whatever byte in file
c) Try to push editall
d) The error of file integrity generate a Two Error Dialog

**Comment by Arch23** [comment]
fixed the second bug by breaking out of the loop when the first edit fail integrity and not trying to redraw the main window if the exception is thrown.
