### ISSUE TITLE
Small window

### ISSUE THREAD

**Issue by Arch23** [ecsanchesjr/ProjetoSeguranca#7]
In the change password window, the text is cropped.
![image](https://user-images.githubusercontent.com/13290488/30675006-5514c86a-9e54-11e7-9338-7a5496c5e5b6.png)

**Comment by gabriel-de-abreu** [comment]
![spectacle n32081](https://user-images.githubusercontent.com/21090026/30675105-fea517ae-9e54-11e7-9ba3-724ce5789398.png)
I set the label to wrap the text, now it won't crop the text anymore, besides, I increased the maximum height, doing so, even the bigger nicknames won't crop.
